### ISSUE TITLE
Create subset of FAOSTAT data

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/datamart-api#108]
The FAOSTAT is huge. We need to create a subset. As a first cut let's just keep rows with "Ethiopia" in the `Area` column. If it is still too big then we can drop CSV files that do not contain indicators of interest to WM.

The entire FAOSTAT dump is in the FAOSTAT.zip file. This zip file contains nested zip files, which unzipped contains the actual CSV data files.
FAOSTAT shared dir:  https://drive.google.com/drive/folders/1rtInCXCPMMzmjL5TNQKQzyenXyu2el8f?usp=sharing

This document contains list of indicators relevant to WM:
[Relevant Indicators for Uncharted to Update_BG ASG.docx](https://github.com/usc-isi-i2/datamart-api/files/5555426/Relevant.Indicators.for.Uncharted.to.Update_BG.ASG.docx)

**Comment by dgarijo** [comment]
I have filtered the files, the size gets reduced significantly. You can find them in https://drive.google.com/drive/u/1/folders/1OfODgLzHpTp_rusBA1MnZ1H83IOIgoDy

There are 2 files that don't follow the conventions of the rest, so these are empty.
