### ISSUE TITLE
Update T2WML tutorial by Dec 1

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/datamart-api#112]
+ Need to update annotations to include tag row.
+ Explain `date` type that automatically guess date formats

**Comment by dgarijo** [comment]
Updated in https://github.com/usc-isi-i2/t2wml/commit/f76a634a564e9155813b83350e1b8df8ea45d863. See https://github.com/usc-isi-i2/t2wml/tree/master/tutorial
