### ISSUE TITLE
Make sure the PUT of `/properties` uses a database transaction

### ISSUE THREAD

**Issue by zmbq** [usc-isi-i2/datamart-api#149]
The PUT handler of the `/properties` endpoint deletes edges and then creates new ones. This needs to be done inside one transaction.

To do so, we need to pass a connection to `import_kgtk_dataframe` and from there to `import_kgtk_tsv`, open this connection in the PUT handler and use it for deleting as well.

**Comment by saggu** [comment]
It is working as described. Works for PUT/POST of entities and properties. Closing
