### ISSUE TITLE
Implement delete variable metadata api

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/datamart-api#24]
Deletes all the variable metadata, there should be no canonical data uploaded to the variable being deleted. User should call the delete data api for this variable before attempting to delete this variable.

```
delete /metadata/datasets/{dataset_id}/variables/{variable_id}
```

Also, implement the delete metadata for all variables
```
delete /metadata/datasets/{dataset_id}/variables
```

The above endpoint should support variables as url parameters,
```
delete /metadata/datasets/{dataset_id}/variables?variable=a_variable&variable=other_variable
```

**Comment by zmbq** [comment]
Implemented in branch `itay/delete-variable-metadata', please try it out.

**Comment by saggu** [comment]
@zmbq I tested the API, it is working for individual variables, but not for all variables and multiple variables. Specifically this part of API as described in the main comment is not working ,

**Not Implemented**
Also, implement the delete metadata for all variables

`delete /metadata/datasets/{dataset_id}/variables`

The above endpoint should support variables as url parameters,
`delete /metadata/datasets/{dataset_id}/variables?variable=a_variable&variable=other_variable`


I changed the return message and status code

**Comment by zmbq** [comment]
Sorry about that, I changed the implementation.

Since deleting all the variables takes some time, I've added the same limit functionality of getting multiple variables. If we do need to delete all of them at a once, I will change the logic a bit to avoid looping over all variables in the dataset.

Committed to branch `itay/delete-variable-metadata`

**Comment by saggu** [comment]
I have tested the API, it  is implemented as specified. Merged in `development` branch.

Closing the issue
