### ISSUE TITLE
Generate location columns for main subjects that are not places

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/datamart-api#25]
Based on our discussion, I have added `P131` qualifiers to the datapoints.  `node2` of the qualifier is the most specific location qnode.

Please use the dataset below to test. To import the dataset do:

1. Create a dataset with dataset_id = `awsd` using this metadata:
```
{'dataset_id': 'awsd',
 'description': 'The Aid Worker Security Database (AWSD) records major '
                'incidents of violence against aid workers, with incident '
                'reports from 1997 through the present. Initiated in 2005, to '
                'date the AWSD remains the sole comprehensive global source of '
                'this data, providing the evidence base for analysis of the '
                'changing security environment for civilian aid operations.',
 'name': 'Aid Worker Security Database (AWSD)',
 'url': 'https://aidworkersecurity.org/'}
```
2. Use the `script/import_tsv_postgres.py ` to import the `kgtk-edges.tsv` file.

[kgtk-edges.zip](https://github.com/usc-isi-i2/datamart-api/files/4991798/kgtk-edges.zip)

**Comment by kyao** [comment]
With the changes the location columns are working!

**Comment by kyao** [comment]
We need a way to avoid name conflicts, perhaps create a some kind of naming schema by adding a prefix

**Comment by zmbq** [comment]
What are we going to do with this?
