### ISSUE TITLE
Location coordinates returned by `/datasets/{dataset_id}/variables/{variable_id}` is incorrect (constant)

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/datamart-api#26]
Steps to reproduce:
1. import this file
[aid-kgtk-edges.csv.gz](https://github.com/usc-isi-i2/datamart-api/files/4998075/aid-kgtk-edges.csv.gz)

2. Notice the data has `P276` edges with coordinates
3. Get data back `/datasets/TESTAID/variables/gender_female` or any variable in the dataset
4. The coordinates are always `POINT(40.0, 9.0)` which I believe are Ethiopia's (the country)

We should get back the coordinates we put in.

**Comment by zmbq** [comment]
This is actually intentional. It was my understanding that the coordinate should be that of the location, and not the one connected with an edge to the timepoint. I can change it, but then we might miss the coordinate if there is no explicit qualifier. Perhaps we should have two coordinates?

**Comment by szeke** [comment]
@saggu The datatype of P276 is item, not globe coordinates. The property to store coordinates is P625. 

If a variable has a coordinates qualifier, we should store them in P625. When we return the data I suggest we have two coordinates columns. One is the location coordinates, and the other the P625 coordinates, which we will return if available.

**Comment by saggu** [comment]
@kyao changes required in the data schema.

**Comment by zmbq** [comment]
We just need two names. Perhaps region_coordinates for the default - region based one? The other name will be provided in the annotations, as it's just another column, isn't it?
Do note that all this is going to require some hard-coding unless we have qualifier type metadata.

**Comment by kyao** [comment]
I am having trouble adding a P625 qualifier using t2wml. I think it is not my misunderstanding on usage but an actual bug. I will create an issue.

**Comment by kyao** [comment]
The current code that returns location coordinate always returns the country coordinate. It should return the location coordinate of the most specific admin region.

**Comment by szeke** [comment]
@kyao Does T2WML know the correct data type for P625?

**Comment by kyao** [comment]
Yes, it knows it is a globe coordinate

**Comment by szeke** [comment]
What is the bug?

**Comment by kyao** [comment]
Does coordinate definition require a globe field? Even if it does t2wml seems to be misnaming the corresponding kgtk column ` node2;kgtk:globe`. An extra leading space is added to the name.

**Comment by szeke** [comment]
Sounds like an issue for the t2wml GitHub

**Comment by kyao** [comment]
@zmbq Here is another dataset with coordinates stored correctly using the P625 property. 

The metadata defines all the variable qualifiers. There maybe more than one location related qualifier.  This breaks the assumption here: https://github.com/usc-isi-i2/datamart-api/blob/master/db/sql/dal/variables.py#L246
We probably should pick the most specific location: P131, P2006190003, P2006190002, P2006190001, P17

Also, the tar file contains the file properties-exploded.tsv, which defines the names of properties that we created like P2006190001.

[data.tar.gz](https://github.com/usc-isi-i2/datamart-api/files/5005292/data.tar.gz)

To use this dataset:
1. untar the file
2. import edge file properties-exploded.tsv
3. define a dataset with dataset_id awsd
4. import edge file kgtk-edges.tsv

**Comment by saggu** [comment]
use `region_coordinates`  for coordinates

**Comment by saggu** [comment]
@zmbq It does not look like fixed. I am still getting constant coordinates back and the column name is still `coordinate`.

I am testing in `development` branch

**Comment by zmbq** [comment]
@saggu , we use the location qualifier to filter locations (based on the URL parameter). If there is more than one location qualifier, which one do we use for filtering? Say you only want things in Ethiopia - which qualifier should be consulted?

The code now just checks for P17, P131, P200619001..P200619003 qualifiers and decides these are location qualifiers. I think this is wrong. In general I fill a little lost regarding the handling of locations in the data. I think I need a quick explanation of how locations are stored in relation to data points - all the options we have - and how we're going to select which is the *main* location - the one we filter by.

**Comment by saggu** [comment]
This issue is also superseded by #30 . Closing
