### ISSUE TITLE
Get data API , eg: `/datasets/OECD/variables/aquaculture`  is returning extra column `stated in`

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/datamart-api#27]
Please see the screenshot

![image](https://user-images.githubusercontent.com/6811931/89330515-3e07af80-d645-11ea-8cc0-4ce9ee5f2468.png)

I am not sure how and when this was introduced. Let me know if you can replicate this @kyao @zmbq

**Comment by zmbq** [comment]
Are you referring to the fixed coordinate? We are supposed to have to coordinate fields, one for the location and one as a qualifier. I haven't implemented it since we need to decide on column names (as well as resolve other naming issues we have). We should discuss this.

**Comment by saggu** [comment]
no, there is `stated_in` and `stated in` columns in the returned file

**Comment by saggu** [comment]
Can't be replicated if I recreate the database from the backup. Looks like we are introducing a qualifier called `stated in` in some dataset. Will keep an eye out
