### ISSUE TITLE
Time precision is not being returned

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/datamart-api#32]
There is time precision in the dates in the following kgtk exploded egde file

but is not returned in the get canonical data api
[t2wml-ann.csv.gz](https://github.com/usc-isi-i2/datamart-api/files/5031914/t2wml-ann.csv.gz)

![image](https://user-images.githubusercontent.com/6811931/89478685-85756500-d745-11ea-90c9-6736820e7e30.png)

**Comment by zmbq** [comment]
I can't load the annotated file. I've created a dataset called ITAY1 and posted the file to /datasets/ITAY1/annotated . 

First it failed because in `annotated/post.py` you pass the dataset as the first parameter to the validator's validate method. The validate method thinks this is an Excel file, and tries to load it. I changed the call to pass None instead. Then the validation fails, but I can't see the error because after the validation fails, post.py fails because it expects three values to be returned from validate, while only two are returned. So the end result is a 500 error.

It is as if I don't have the correct code for either the validator or the request handler. I'm using the development branch.

**Comment by zmbq** [comment]
Sorry about the assignment mixup, I forgot to update t2wml-annotator, which caused everything to malfunction.

**Comment by zmbq** [comment]
Now that I got the right versions in place, I get validation errors and can't upload the annotated file at all:

```[
    {
        "Error": "Dataset ID in the file is not same as the Dataset ID in the URL",
        "Line Number": 1,
        "Column": "B",
        "Description": "Expected: ITAY1 but got:node1"
    },
    {
        "Error": "Incorrect annotation: First Column",
        "Line Number": 1,
        "Column": "A",
        "Description": "First row in column 1 should be \"dataset\""
    },
    {
        "Error": "Incorrect annotation: First Column",
        "Line Number": 2,
        "Column": "A",
        "Description": "Second row in column 1 should be \"role\""
    },
    {
        "Error": "Incorrect annotation: First Column",
        "Line Number": 3,
        "Column": "A",
        "Description": "Third row in column 1 should be \"type\""
    },
    {
        "Error": "Incorrect annotation: First Column",
        "Line Number": 4,
        "Column": "A",
        "Description": "Fourth row in column 1 should be \"description\""
    },
    {
        "Error": "Incorrect annotation: First Column",
        "Line Number": 5,
        "Column": "A",
        "Description": "Fifth row in column 1 should be \"name\""
    },
    {
        "Error": "Incorrect annotation: First Column",
        "Line Number": 6,
        "Column": "A",
        "Description": "Sixth row in column 1 should be \"unit\""
    },
    {
        "Error": "Annotation missing: variable",
        "Line Number": 2,
        "Column": -1,
        "Description": "Annotation spreadsheet should have at least one column annotated as \"variable\""
    },
    {
        "Error": "Annotation missing: time",
        "Line Number": 2,
        "Column": -1,
        "Description": "Annotation spreadsheet should have at least one column annotated as \"time\""
    },
    {
        "Error": "Annotation invalid",
        "Line Number": 2,
        "Column": -1,
        "Description": "Either \"location\" or \"main subject\" should be present as annotation for a column. None of the columns are annotated as \"location\" or \"variable\""
    },
    {
        "Error": "Roles in following column(s) are invalid: B,C,D,E,F,G,H,L",
        "Line Number": 2,
        "Column": "B,C,D,E,F,G,H,L",
        "Description": "Valid roles are one of the following: main subject,time,location,variable,qualifier,unit"
    }
]```

I know how to fix the first one (with the wrong dataset name), but not the others.

**Comment by saggu** [comment]
@zmbq please import this file directly into database. This is a KGTK exploded edge file

This file is not supposed to be uploaded via the `/annotated` API. Sorry for the confusion

**Comment by zmbq** [comment]
The attached file can't be imported as is. For future reference, these are the steps necessary to reproduce the bug

1. Convert the file to TSV
2. Create the dataset by POSTing to `/metadata/datasets`:
```
{
    "dataset_id": "t2wml_test_02",
    "description": "t2wml test #2",
    "name": "t2wml_test_02",
    "url": "https://nowhere.org"
}
```
3. Import the TSV file

Now you can query `/datasets/t2wml_test_002/variables/ingo` and see the time precision is N/A on every row.

**Comment by zmbq** [comment]
The problem was the precision was retrieved as `11.0` for some reason, which caused a simple conversion issue - `int('11.0')` throws a ValueError.

Fixed in the `development` branch.

**Comment by saggu** [comment]
@zmbq I will have detailed steps to reproduce, my bad.

This is working now, closing the issue
