### ISSUE TITLE
Coordinates missing

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/datamart-api#37]
![image](https://user-images.githubusercontent.com/6811931/89480109-5eb92d80-d749-11ea-883d-7c39e2e75e0d.png)

https://docs.google.com/spreadsheets/d/1cRjjeehqjW7604sLHi7OB5hAYfPGuNjCWXF3_wK5fvk/edit#gid=1158629569

Coordinates missing for `admin1`

**Comment by zmbq** [comment]
The database only has P625 edges for countries.

**Comment by szeke** [comment]
@zmbq can you add the coordinates for all admin regions?

**Comment by zmbq** [comment]
I don't have this information... Do we have a kgtk file with all the edges? Or an Excel file with this information for each region?

**Comment by szeke** [comment]
I can make a file that has P625 for every q-node that has P625. 

I don't have handy a file that has the q-nodes for all the regions. If you five it to me I can filter the P625 file, or you can filter it on your end.

**Comment by saggu** [comment]
@szeke https://github.com/usc-isi-i2/datamart-api/blob/master/metadata/region.csv This is what @kyao compiled. It has admin1, admin2, admin3 and country qnodes for all countries

**Comment by szeke** [comment]
[P625-for-regions.tsv.gz](https://github.com/usc-isi-i2/datamart-api/files/5039288/P625-for-regions.tsv.gz)
@zmbq P625 for all admin region q-nodes (may be incomplete because based on 2018 Wikidata)

**Comment by szeke** [comment]
Adding exploded version of the file:

[P625-for-regions-exploded.tsv.gz](https://github.com/usc-isi-i2/datamart-api/files/5043037/P625-for-regions-exploded.tsv.gz)

**Comment by zmbq** [comment]
The exploded file does not contain long and lat values, just node2. It wasn't exploded properly.

**Comment by zmbq** [comment]
The file had one bad row with an empty edge- Q24064988-P625-1 . I had to remove it.

I have updated the spreadsheet here: https://docs.google.com/spreadsheets/d/17V3QMUGdm3TW4vQKcM-Zhm9tNUJVLSX02D1SmF_pF3E/edit#gid=0 and the files in the kgtk Google folder.

**Comment by saggu** [comment]
This issue is now resolved, in that I am getting coordinates back for admin1 in the case reported above.
However this issue is now superseded by issue #30 

![image](https://user-images.githubusercontent.com/6811931/89926219-69e0e300-dbb9-11ea-803a-932def88452e.png)


Closing this issue, will track progress in #30
