### ISSUE TITLE
Implement `delete` dataset API

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/datamart-api#39]

**Comment by zmbq** [comment]
Pushed to development.

Deleting a dataset only works if the is no variable metadata in the dataset, so make sure you delete all variables and their metadata first.

**Comment by saggu** [comment]
Maybe we should add a `force=True` parameter. Which deletes data, metadata for variables first and then deletes `dataset`.

Discuss in today's meeting

**Comment by saggu** [comment]
Working as expected. Keeping it open to add the `Force=True` parameter

**Comment by saggu** [comment]
Implemented, adding `?force=true` to url will obliterate the dataset
