### ISSUE TITLE
if multiple columns, annotated as `variable`, have same header, they should be considered as same variable

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/datamart-api#44]
If the users want to distinguish them, they can add a different `name` in the annotation

**Comment by zmbq** [comment]
How is this supposed to work without the `name` annotation? If both columns map to the same variable, their cells must contain the same values. Otherwise we're going to have two different values for the same variable on the same datapoint, right?

**Comment by saggu** [comment]
This has been implemented in datamart-api and t2wml-annotation.

Here is how this works:
1. if 2 variables have same header, but different `name`, then they are treated as separate variables. The column header will be renamed anyway with a numerical suffix separated by `_`
2. if 2 variables have same header, and blank or same `name`, they'll be treated as same variable. Column header will be renamed in a similar fashion as described in 1.

Potentially can wreck havoc in the data if the users meant to make the variables different but left the `name` blank.

I will create another issue to handle this in data validation.

Closing this issue
