### ISSUE TITLE
Some files have Admin1, Admin2 and Admin3  codes in the Ethiopia

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/datamart-api#49]
We cannot wikify these at the moment. We should add these code in the wikifier and maybe have the option of annotatiing `type=admin1_code, admin2_code or admin3_code`

**Comment by kyao** [comment]
The `Spatial units` tab of the census dataset has the region, zone and woreda codes. The dataset file `Population_Housing_Census_Atlas_of_Ethiopia_2007.xls` is in the `Ethiopian Data Registration Test` shared folder.

![image](https://user-images.githubusercontent.com/1087657/90184222-a18e8d00-dd69-11ea-8c1b-046a2aedeb1c.png)

**Comment by kyao** [comment]
The census dataset directly uses the `W_CODE`:
![image](https://user-images.githubusercontent.com/1087657/90184681-54f78180-dd6a-11ea-91fa-d62a4fc027d5.png)

However, the `Annual Producer Price` and `Annual retail price` datasets explodes the woreda code into three columns, and they use string name for the region:
![image](https://user-images.githubusercontent.com/1087657/90185016-e109a900-dd6a-11ea-9a46-34250db2e160.png)

**Comment by kyao** [comment]
Use `admin3` type, no need to use `admin3_code`.

Done
