### ISSUE TITLE
Improve non-bulk import performance

### ISSUE THREAD

**Issue by zmbq** [usc-isi-i2/datamart-api#66]
Importing can take a long time (non-bulk import). Try to see whether we can optimize the update:

* Stop using SQLAclhemy for INSERTs
* Combine INSERT statements

**Comment by zmbq** [comment]
The `itay/fast-insert` branch contains a fix to importing edges into Postgres. *I did not test it thoroughly, and I'm not 100% sure the edges are written as they should to the database*, so please test it and let me know if there are issues ASAP, so I can fix it in time for the demonstration. Do not demonstrate it yet, obviously.

**Comment by saggu** [comment]
This  has been tested and merged into `master`. Closing
