### ISSUE TITLE
Periodic data dumps for the whole database (nightly)

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/datamart-api#75]
Create a tar gzip file containing data for all variables in all datasets and make it available to be downloaded via an endpoint

**Comment by zmbq** [comment]
What format should we used for this? I have a few ideas.

1. A dump of the Postgres database.
2. A tar.gz of a folder containing one subfolder per dataset, with one subfolder per variable. Each variable subfolder will contain one JSON file for the variable metadata and CSV file with the data.

The problem with the first solution is that they won't be able to use it for anything other than restoring the database back. The problem with the second solution is that there's no way to restore the database from it. Perhaps we need both?

**Comment by saggu** [comment]
They want canonical data for all variables in all the datasets. This use case is very particular. They tried to download the data for the dataset UAZ which has >1000 variables, nginx timed out and server got super busy.

We suggested generating dumps for all data every night which they can access via an API.

1. a subfolder for each dataset
2. a canonical file for each variable in the dataset
3. create tar gzip file with the data
4. Make it available via an API endpoint

**Comment by kyao** [comment]
Just need a dump script for now. @zmbq

**Comment by zmbq** [comment]
Implemented the `script/dump-datasets.py` script. It accepts a mandatory directory parameter for storing the dumps, and two optional parameters -the datamart URL and the package name (a tar.gz file that will contain the files in the output directory).

Running it on the causx database backup takes less than 10 minutes on my new laptop (which is quite powerful but still - a laptop).

**Comment by saggu** [comment]
For me to test.
