### ISSUE TITLE
Automate database backup and restore when the docker is stopped and started

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/datamart-api#81]
1. There is no docker volume, so when the docker container is stopped, the data is lost
2. Keep track of which datasets/variables were created/inserted data for since the last time the docker was started. 
3. And then create a backup with just this data when the docker is stopped.
4. Optionally, the users want the ability to restore the backed up data.

Maybe we can create API to do this and put it on users to call the API.

**Comment by zmbq** [comment]
Why isn't there a docker volume?

**Comment by szeke** [comment]
They don't allow it for whatever reason. We can have a preloaded DB in the docker, and user loaded files cannot be saved and will have to br reloaded every time the system starts

**Comment by kyao** [comment]
We will create a sql dump with all the static datasets (~74 variables). On datamart restart they (TwoSix, STR) will re-upload the additional datasets.

**Comment by zmbq** [comment]
Is this still necessary? In our weekly call two weeks ago we discussed a Docker volume that is not accessible from the host file-system. Is this enough?
