### ISSUE TITLE
Annotation without "data" in col 1

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/datamart-api#87]
Annotation without "data" in col 1 passes validation

**Comment by saggu** [comment]
that is not an issue because in this case `data_row` = `header_row` + 1

mentioned here https://t2wml-annotation.readthedocs.io/en/latest/


I am fixing this in https://github.com/usc-isi-i2/t2wml-annotation/blob/master/annotation/generation/generate_t2wml.py#L198

**Comment by saggu** [comment]
Changed my mind because of addition of a new `tag` row in the annotations. From now on, `header` and `data` annotations will be required

**Comment by saggu** [comment]
Fixed, absence of `data` annotation will return validation error
