### ISSUE TITLE
POST API overwrites variable values of a different timestamp

### ISSUE THREAD

**Issue by Otamio** [usc-isi-i2/datamart-api#92]
Posting annotated sheets to a dataset will overwrite the values of variables of a different timestamp in that dataset.

E.g. Posting annotated 'FSI-2020.xlsx' to 'FSI' will overwrite the values of variables like 'e1_economy' from the years 2006-2019, if they have been stored in Datamart.

The code is here:
https://github.com/Otamio/datamart-api/blob/development/data-refresh/FSI/FSI-Bug.ipynb

**Comment by saggu** [comment]
@Otamio that issue is now fixed in `development`, pull the latest and give it a try again.

**Comment by Otamio** [comment]
@saggu I have reconfigured my environment and everything looks good now.
