### ISSUE TITLE
Rows with empty "tag' is being inserted into database

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/datamart-api#95]
![image](https://user-images.githubusercontent.com/6811931/97762093-c373f200-1ac4-11eb-904e-52982db4dbf6.png)

Ideally, we should not insert empty rows

**Comment by kyao** [comment]
Are those blank node2 cells completely empty? Or, do they contain space characters?

**Comment by saggu** [comment]
completely empty, I think its coming from here https://github.com/usc-isi-i2/t2wml-annotation/blob/master/annotation/generation/annotation_to_template.py#L161

**Comment by kyao** [comment]
That code is for creating the Excel template with the tag column. 

The code that generates the tag edges based on the Excel template is here: https://github.com/usc-isi-i2/t2wml-annotation/blob/master/annotation/generation/wikify_datamart_units_and_attributes.py#L341

It should have skipped generating the tag edge if the cell is empty. Let me try a few test cases.

**Comment by kyao** [comment]
Fix in 2wml-annotation dfe1744
